app/models/flight.py
from flask_admin.contrib.sqla.view import ModelView, func
from app.extensions import db

class Flight(db.Model):
    __tablename__ = 'flights'
    id = db.Column(db.Integer, primary_key=True)
    number = db.Column(db.String(64))
    airport_id = db.Column(db.Integer, db.ForeignKey('airports.id'))
    destination_id = db.Column(db.Integer, db.ForeignKey('locations.id'))

    airport = db.relationship('Airport', back_populates='flights')
    destination = db.relationship('Location', back_populates='flights')

    def __repr__(self) -> str:
        return self.number

    def bar(self):
        from app.models import Airport
        airport = Airport.query.get(1)
        return f"from Flight class: {self}. Also this airport: {airport}"


class FlightView(ModelView):
    can_view_details = True
    # column_choices = {
    #     'airport': [('id', 'name')]
    # }
    column_formatters = dict(
        airport=lambda v, c, m, p: m.airport.name,
        destination=lambda v, c, m, p: f'{m.destination.city}, {m.destination.country}'
    )
    # form_ajax_refs = {
    #     'user': QueryAjaxModelLoader('user', db.session, User, fields=['email'], page_size=10)
    # }
    form_ajax_refs = {
        'airport': {
            'fields': ('name',),
            'placeholder': 'Please select',
            'page_size': 10,
            'minimum_input_length': 0,
        }
    }

    # Example of restricting records that appear in an admin view
    # def get_query(self):
    #     return self.session.query(self.model).filter(
    #         self.model.destination.has(city='Cherry Hill')
    #     )
    # def get_count_query(self):
    #     return self.session.query(func.count('*')).filter(
    #         self.model.destination.has(city='Cherry Hill')
    #     )

app/blueprints/flights/__init__.py
from flask import Blueprint

flights = Blueprint('flights', __name__)

from . import views

app/blueprints/flights/views.py
from flask import redirect, render_template, request, url_for, jsonify, abort, flash
from sqlalchemy.orm import joinedload, noload, contains_eager
from marshmallow import ValidationError

from app.extensions import db
from app.models import *
from app.schemas import FlightSchema

from . import flights

# Reusable query builder
flights_statement = db.select(Flight)\
    .outerjoin(Airport)\
    .outerjoin(Location)\
    .options(
        contains_eager(Flight.airport),
        contains_eager(Flight.destination)
    )
airports_statement = db.select(Airport)
locations_statement = db.select(Location)

@flights.route("/flights", methods=['GET'])
def index():
    """Display list of flights."""
    # flights = Flight.query.get_or_404(1)
    # flights = db.session.execute(db.select(Flight).filter_by(id=1)).one()
    # flights = db.session.execute(db.select(Flight).filter_by(id=1)).scalars().all()
    # flights = db.session.execute(db.select(Flight)).scalars().all()
    # flights = db.session.execute(db.select(Flight))
    # flights_foo = db.get_or_404(Flight, 1)
    flights = db.session.scalars(flights_statement)
    return render_template('flights/index.html', flights=flights)

@flights.route("/flight/load-test")
def load_test():
    try:
        flight_schema = FlightSchema()

        # If you were creating a new flight and airport at the same time
        # Of course you wouldn't have any IDs yet
        # You can probably have one schema but have a different load configuration
        # depending on the endpoint
        # new_flight_json = {
        #     "id": "-1",
        #     "number": "666",
        #     "airport_id": "-1",
        #     "airport": {
        #         "id": "-1",
        #         "name": "My Fake Airport",
        #     },
        # }
        # new_flight = flight_schema.load(new_flight_json, partial=True)

        update_flight_json = {
            # "number": "666",
            "airport": {
                "name": "My Fake Airport",
            },
            "destination_id": "1"
        }

        new_flight = flight_schema.load(update_flight_json, partial=("airport_id",))

        # db.session.add(flight)
        # db.session.flush()
        # db.session.commit()
        # flight = Flight.query.first()
        
        # print(f"AIRPORT ID: {new_flight.airport_id}")
        return jsonify(flight_schema.dump(new_flight))
    except ValidationError as error:
        return jsonify(error.messages)

@flights.route("/flight/update-test", methods=['GET'])
def update_test():
    # Maybe a partial update only works if load_instance=True
    flight_schema = FlightSchema(load_instance=True)

    # existing_flight = Flight.query.get(1)

    existing_flight_json = {
        "id": "1",
        # "number": "1",
        # "airport_id": 3,
        # "destination_id": 2
    }
    existing_flight = flight_schema.load(existing_flight_json, partial=True)

    update_flight_json = {
        "number": "9000",
    }

    # new_flight = FlightSchema(partial=True).load(update_flight_json)
    data = flight_schema.load(update_flight_json, instance=existing_flight, partial=True)

    # db.session.add(flight)
    # db.session.flush()
    db.session.commit()
    # flight = Flight.query.first()

    return jsonify(FlightSchema().dump(data))

@flights.route("/flight/dump-test", methods=['GET'])
def dump_test():
    flight_schema = FlightSchema()
    # flight = Flight.query.first()
    # flight = Flight.query.options(joinedload(Airport.flights)).first()
    # flight = Flight.query.options(noload('airport')).first()
    # flight = Flight.query.join(Airport).first()


    flight = db.session.query(Flight)\
        .options(joinedload(Flight.airport))\
        .filter(Flight.id == 1)\
        .one()

    airport_loaded = False
    load_triggered = False

    # if flight.airport:
    #     load_triggered = True 

    # if 'airport' in flight.__dict__:
    #     airport_loaded = True

    # response = {
    #     "id": flight.id,
    #     "number": flight.number,
    #     "airport_loaded": airport_loaded,
    # }
    # return jsonify(response), 201

    return jsonify(flight_schema.dump(flight))

@flights.route("/flights/create", methods=['GET'])
def create():
    """Display form to create a new flight."""
    airports = db.session.scalars(airports_statement)
    locations = db.session.scalars(locations_statement)
    return render_template('flights/create.html', airports=airports, locations=locations)

@flights.route("/flights/save", methods=['POST'])
def save():
    """Persist the new flight."""
    # errors = create_flight_schema.validate(request.form)
    # if errors:
    #     abort(400, str(errors))

    try:
        # flight_schema = CreateFlightInputSchema()
        flight_schema = FlightSchema()
        flight = flight_schema.load(request.form)

        # flight = Flight()
        # flight.number = request.form['number']
        # flight.airport_id = request.form['airport_id']
        # flight.destination_id = request.form['destination_id']

        db.session.add(flight)
        db.session.commit()

        return redirect(url_for('flights.index'))
    except ValidationError as error:
        flash(error.messages)
        return redirect(url_for('flights.create'))


@flights.route("/flights/edit/<id>", methods=['GET'])
def edit(id):
    """Display form to edit an existing flight."""
    flight_statement = flights_statement.filter(Flight.id == id)
    flight = db.one_or_404(flight_statement)

    # flight_statement = db.select(Flight).filter_by(id=id)
    # flight = Flight.query.get_or_404(id)
    # flight = db.session.scalars(statement).one()
    # flight = db.session.scalar(flight_statement)

    airports = db.session.scalars(airports_statement)
    locations = db.session.scalars(locations_statement)

    return render_template('flights/edit.html', flight=flight, airports=airports, locations=locations)

@flights.route("/flights/update/<id>", methods=['POST'])
def update(id):
    """Persist the flight changes."""
    try:
        flight_schema = FlightSchema(load_instance=True)

        flight_statement = db.select(Flight).filter_by(id=id)
        existing_flight = db.session.scalar(flight_statement)

        # errors = flight_schema.validate(request.form)
        # if errors:
        #     abort(400, str(errors))

        flight = flight_schema.load(request.form, instance=existing_flight, partial=True)

        # flight.number = request.form['number']
        db.session.commit()

        return redirect(url_for('flights.edit', id=id))
    except ValidationError as error:
        
        flash(error.messages)
        return redirect(url_for('flights.edit', id=id))

@flights.route("/flights/delete/<id>")
def delete(id):
    """Delete the flight."""
    flight_statement = db.select(Flight).filter_by(id=id)
    flight = db.session.scalar(flight_statement)
    db.session.delete(flight)
    db.session.commit()
    return redirect(url_for('flights.index'))

app/templates/flights/create.html
{% extends "layout.html" %}
{% set active_page = "flights" %}

{% block title %}Flight{% endblock %}

{% block page_content %}
<h1>Create New Flight</h1>

<form action="{{ url_for('flights.save') }}" method="post">
  <div class="form-group">
    <label for="flightNumber">Number</label>
    <input type="text" class="form-control" id="flightNumber" name="number">
  </div>

  <div class="form-group">
    <label for="flightAirport">Airport</label>
    <select class="form-control" id="flightAirport" name="airport_id">
      <option value="error">Do not select this!</option>
      {% for airport in airports %}
      <option value="{{airport.id}}">{{ airport }}</option>
      {% endfor %}
    </select>
  </div>

  <div class="form-group">
    <label for="flightDestination">Destination</label>
    <select class="form-control" id="flightDestination" name="destination_id">
      {% for location in locations %}
      <option value="{{location.id}}">{{ location }}</option>
      {% endfor %}
    </select>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock page_content %}

app/templates/flights/edit.html
{% extends "layout.html" %}
{% set active_page = "flights" %}

{% block title %}Flight{% endblock %}

{% block page_content %}
<h1>Flight</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Number</th>
      <th scope="col">Airport</th>
      <th scope="col">Destination</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{ flight.id }}</th>
      <td>{{ flight.number }}</td>
      <td>{{ flight.airport }}</td>
      <td>{{ flight.destination }}</td>
    </tr>
  </tbody>
</table>

<form action="{{ url_for('flights.update', id=flight.id) }}" method="post">
  <div class="form-group">
    <label for="flightNumber">Number</label>
    <input type="text" class="form-control" id="flightNumber" name="number" value="{{ flight.number }}">
  </div>

  <div class="form-group">
    <label for="flightAirport">Airport</label>
    <select class="form-control" id="flightAirport" name="airport_id">
      <option value="error">Do not select this!</option>
      {% for airport in airports %}
      <option value="{{airport.id}}" {% if airport.id == flight.airport.id %}selected{% endif %}>{{ airport }}</option>
      {% endfor %}
    </select>
  </div>

  <div class="form-group">
    <label for="flightDestination">Destination</label>
    <select class="form-control" id="flightDestination" name="destination_id">
      {% for location in locations %}
      <option value="{{location.id}}" {% if location.id == flight.destination.id %}selected{% endif %}>{{ location }}</option>
      {% endfor %}
    </select>
  </div>

  <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock page_content %}

app/templates/flights/index.html
{% extends "layout.html" %}
{% set active_page = "flights" %}

{% block title %}Flights{% endblock %}

{% block page_content %}
<div class="d-flex justify-content-between align-items-center">
  <h1>Flights</h1>
  <span>
    <a class="btn btn-primary" href="{{ url_for('flights.create') }}" role="button">Create New</a>
  </span>
</div>
<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Number</th>
      <th scope="col">Airport</th>
      <th scope="col">Destination</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    {% for flight in flights %}
    <tr>
      <th scope="row"> <a href="{{ url_for('flights.edit', id=flight.id) }}">{{ flight.id }}</a></th>
      <td>{{ flight.number }}</td>
      <td>{{ flight.airport }}</td>
      <td>{{ flight.destination }}</td>
      <td>
        <a class="btn btn-primary btn-sm" href="{{ url_for('flights.delete', id=flight.id) }}" role="button">
          <i class="fa fa-trash" aria-hidden="true"></i>
        </a>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock page_content %}